# Generated by Django 4.2.21 on 2025-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cart_recipe_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
